@startuml

' Declaração da classe Cachorro que implementa as interfaces IAnimal e IPet
class Cachorro {
    + comer()
    + dormir()
    + fazerSom()
    + brincar()
}

() IAnimal

' Relacionamento entre as interfaces e a classe
IAnimal -up--# Cachorro


@enduml
