@startuml

left to right direction
skinparam packageStyle rectangle
actor "Usuário do\nsistema" as us
actor Usuario as u
actor Cliente as c
actor Administrador as adm
actor Patrocinador as p
actor Fabricantes as f
actor Varejistas as v
actor "Atendentes de\nSuporte" as a

rectangle "Sistema de Controle de Garantias de Produtos (SCGP)" {
    package "Produto" {
        usecase "Manter\nprodutos" as uc_manter_produtos
        usecase "Contratar\nassinatura" as uc_contratar_assinatura
        usecase "Divulgar\nprodutos" as uc_divulgar_produtos
        usecase "Vender dados\nprodutos" as uc_vender_dados_produtos
        usecase "Notificar cliente\nsobre garantia" as uc_notificar_cliente_sobre_garantia
        usecase "Manter garantias" as uc_manter_garantias
    }
    package "Cliente" {
        usecase "Manter\nclientes" as uc_manter_clientes
        usecase "Comunicar\nclientes" as uc_comunicar_clientes
        usecase "Manter comunicação\ncom clientes" as uc_manter_comunicacao_clientes
    }
    usecase "Manter\nfabricantes" as uc_manter_fabricantes
    usecase "Contatar\nfabricantes" as uc_contatar_fabricantes
}

us <|-- u
us <|-- adm
u <|-- c
u <|-- a
u <|-- p
u <|-- f
u <|-- v

c -- uc_manter_garantias
uc_manter_garantias <. uc_manter_produtos: <<include>>

c -- uc_manter_produtos
adm -- uc_contratar_assinatura

adm -- uc_vender_dados_produtos
uc_vender_dados_produtos .> uc_manter_produtos: <<include>>

adm -- uc_divulgar_produtos
uc_divulgar_produtos .> uc_manter_produtos: <<include>>

adm -- uc_manter_clientes

adm -- uc_manter_comunicacao_clientes
' uc_manter_comunicacao_clientes .> uc_manter_clientes: <<include>>

v -- uc_comunicar_clientes
' uc_comunicar_clientes .> uc_manter_clientes: <<include>>

c -- uc_notificar_cliente_sobre_garantia

adm -- uc_manter_fabricantes
f -- uc_manter_fabricantes

note "somente consulta" as N1

c -- uc_manter_fabricantes
c .. N1
N1 .. uc_manter_fabricantes

c -- uc_contatar_fabricantes
uc_contatar_fabricantes .> uc_manter_fabricantes: <<extend>>
@enduml

