@startuml

left to right direction
skinparam packageStyle rectangle
actor Cliente as c

rectangle "SCGP" {
    usecase "Manter produto" as uc1
    usecase "Manter garantia" as uc2
}

c -- uc1
uc1 <. uc2: <<extend>>

@enduml