@startuml

left to right direction
skinparam packageStyle rectangle
actor Cliente as c

rectangle "Manter produtos" {
    usecase "Manter produto" as uc1
    usecase "Manter garantias" as uc2
}

c -- uc1
uc1 .> uc2: <<include>>

@enduml