source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins
gem 'wdm', '>= 0.1.0'
gem "webrick", "~> 1.8"
gem "public_suffix", "~> 4.0.7"
gem "jekyll"
gem "minimal-mistakes-jekyll"

group :jekyll_plugins do
  gem 'jekyll-seo-tag'
end